#!/usr/bin/with-contenv bash
# shellcheck shell=bash

IFS="|" read -r -a CLI_OPTIONS <<< "$CLI_OPTIONS_STRING"
IMAGENAME=${CLI_OPTIONS[0]%%:*}
if [[ ${CLI_OPTIONS[0]} == *":"* ]]; then
    TAGNAME=${CLI_OPTIONS[0]##*:}
else
    TAGNAME="latest"
fi

if [[ -n ${LOCAL} ]]; then
    OUTPUTNAME="${IMAGENAME}-${TAGNAME}-LOCAL"
else
    OUTPUTNAME="${IMAGENAME}-${TAGNAME}"
fi

if [[ -n ${SVG} ]]; then
    s6-setuidgid abc d2 "/output/${OUTPUTNAME}.d2" "/output/${OUTPUTNAME}.svg"
    chmod 644 "/output/${OUTPUTNAME}.d2" "/output/${OUTPUTNAME}.svg"
else
    chmod 644 "/output/${OUTPUTNAME}.d2"
fi
